[[session]]
name = "main"
path = "~"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "yazi"

[[session]]
name = "ps"
path = "~/200 Areas/Problem Solving Index/"
startup_command = "yazi"
